export default [
	{ attribute: 'name', value: 'keywords', content: 'contactpage' },
	{ attribute: 'name', value: 'geo.position', content: '52.017850;21.904640' },
	{ attribute: 'name', value: 'geo.placename', content: 'Warsaw' },
	{ attribute: 'property', value: 'og:url', content: 'https://example.com' },
	{ attribute: 'property', value: 'og:locale', content: 'pl_PL' },
	{ attribute: 'property', value: 'og:type', content: 'website' },
	{ attribute: 'property', value: 'og:site_name', content: 'Example' },
	{ attribute: 'property', value: 'og:title', content: 'Web pages with ...' },
	{ attribute: 'property', value: 'og:description', content: 'About page ...' },
	{ attribute: 'property', value: 'og:image', content: 'https://example.com/default/logo/logo.webp' },
	{ attribute: 'property', value: 'og:width', content: '700' },
	{ attribute: 'property', value: 'og:height', content: '700' },
	{ attribute: 'name', value: 'twitter:card', content: 'summary' },
	{ attribute: 'name', value: 'twitter:site', content: '@username' },
	{ attribute: 'name', value: 'twitter:title', content: 'Page title | Example' },
	{ attribute: 'name', value: 'twitter:description', content: 'About ...' },
	{ attribute: 'name', value: 'twitter:image', content: 'https://exampel.com/default/logo/logo.webp' },
	{ attribute: 'name', value: 'twitter:image:alt', content: 'Example' },
];
